from django.urls import path, re_path

from .views import (
    api_github_app_disconnect,
    api_github_app_install_url,
    api_project_asset,
    api_project_asset_content,
    api_project_asset_rename,
    api_project_assets,
    api_project_compile,
    api_project_compile_local_result,
    api_local_runtime_claim_job,
    api_local_runtime_heartbeat,
    api_project_create_template,
    api_project_download_zip,
    api_project_detail,
    api_project_file,
    api_project_github_sync,
    api_project_insert,
    api_project_local_runtime,
    api_project_local_runtime_jobs,
    api_project_pdf,
    api_project_pdf_page_count,
    api_project_pdf_page_image,
    api_project_plantuml,
    api_project_read_window,
    api_project_write_window,
    api_project_search,
    api_project_synctex_line,
    api_project_synctex_pdf,
    api_project_tinymist_definition,
    api_project_tinymist_diagnostics,
    api_project_tinymist_format,
    api_project_tinymist_references,
    api_project_tinymist_symbols,
    api_project_typst_citations,
    api_project_typst_preview,
    api_project_typst_preview_restart,
    api_project_section,
    api_project_sections,
    api_project_version_detail,
    api_project_version_rollback,
    api_project_versions,
    api_projects,
    api_project_typst_import,
    api_project_pdf_embed,
    github_app_callback,
)

urlpatterns = [
    path("projects/", api_projects),
    path("projects/<int:project_id>/", api_project_detail),
    path("projects/<int:project_id>/file/", api_project_file),
    path("projects/<int:project_id>/search/", api_project_search),
    path("projects/<int:project_id>/read-window/", api_project_read_window),
    path("projects/<int:project_id>/write-window/", api_project_write_window),
    path("projects/<int:project_id>/files/", api_project_assets),
    path("projects/<int:project_id>/typst-import/", api_project_typst_import),
    re_path(r"^projects/(?P<project_id>\d+)/files/(?P<filename>.+)/content/$", api_project_asset_content),
    re_path(r"^projects/(?P<project_id>\d+)/files/(?P<filename>.+)/rename/$", api_project_asset_rename),
    re_path(r"^projects/(?P<project_id>\d+)/files/(?P<filename>.+)/$", api_project_asset),
    path("projects/<int:project_id>/sections/", api_project_sections),
    path("projects/<int:project_id>/sections/<int:section_index>/", api_project_section),
    path("projects/<int:project_id>/insert/", api_project_insert),
    path("projects/<int:project_id>/versions/", api_project_versions),
    path("projects/<int:project_id>/versions/<int:version_id>/", api_project_version_detail),
    path("projects/<int:project_id>/versions/<int:version_id>/rollback/", api_project_version_rollback),
    path("projects/<int:project_id>/compile/", api_project_compile),
    path("projects/<int:project_id>/compile/local-result/", api_project_compile_local_result),
    path("projects/<int:project_id>/local-runtime/", api_project_local_runtime),
    path("projects/<int:project_id>/local-runtime/jobs/", api_project_local_runtime_jobs),
    path("local-runtime/heartbeat/", api_local_runtime_heartbeat),
    path("local-runtime/jobs/claim/", api_local_runtime_claim_job),
    path("projects/<int:project_id>/plantuml/", api_project_plantuml),
    path("projects/<int:project_id>/create-template/", api_project_create_template),
    path("projects/<int:project_id>/download-zip/", api_project_download_zip),
    path("projects/<int:project_id>/github-sync/", api_project_github_sync),
    path("github/install-url/", api_github_app_install_url),
    path("github/disconnect/", api_github_app_disconnect),
    path("projects/<int:project_id>/pdf/", api_project_pdf),
    path("projects/<int:project_id>/pdf-page-count/", api_project_pdf_page_count),
    path("projects/<int:project_id>/pdf-embed/", api_project_pdf_embed),
    path("projects/<int:project_id>/pdf-page-image/", api_project_pdf_page_image),
    path("projects/<int:project_id>/synctex/line/", api_project_synctex_line),
    path("projects/<int:project_id>/synctex/pdf/", api_project_synctex_pdf),
    path("projects/<int:project_id>/tinymist/diagnostics/", api_project_tinymist_diagnostics),
    path("projects/<int:project_id>/tinymist/symbols/", api_project_tinymist_symbols),
    path("projects/<int:project_id>/tinymist/format/", api_project_tinymist_format),
    path("projects/<int:project_id>/tinymist/definition/", api_project_tinymist_definition),
    path("projects/<int:project_id>/tinymist/references/", api_project_tinymist_references),
    path("projects/<int:project_id>/typst/citations/", api_project_typst_citations),
    path("projects/<int:project_id>/typst-preview/restart/", api_project_typst_preview_restart),
    re_path(r"^projects/(?P<project_id>\d+)/typst-preview/(?P<subpath>.*)$", api_project_typst_preview),
]
