from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

from projects.pre_compile import PreCompileJob, PreCompileResult, register
from projects.typst_auto_generated import (
    inject_auto_import_into_reachable_typst,
    remove_auto_imports_from_all_typst,
)

_MANIFEST_PATH = ".smarttex/pdf_includes.json"
_CACHE_DIR = ".smarttex/cache/pdf-pages"
_HELPER_PATH = ".smarttex/auto_generated/pdf_includes.typ"
# Use /-prefixed path so Typst resolves it from --root regardless of where main.typ lives
_IMPORT_LINE = '#import "/.smarttex/auto_generated/pdf_includes.typ": smarttex-include-pdf'

_DEFAULT_SCALE = 4.0  # ~288 DPI — high quality for embedded pages
_PAGE_EXT = ".jpg"
_JPEG_QUALITY = 94  # visually lossless for document pages, ~4-6x smaller than PNG


def load_manifest(workdir: Path) -> dict[str, dict]:
    path = workdir / _MANIFEST_PATH
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_manifest(workdir: Path, manifest: dict[str, dict]) -> None:
    path = workdir / _MANIFEST_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _safe_cache_name(pdf_rel: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "_", pdf_rel).strip("_") or "pdf"


def _render_pdf_pages(pdf_path: Path, cache_dir: Path, workdir: Path, scale: float = _DEFAULT_SCALE) -> list[str]:
    import pypdfium2 as pdfium

    doc = pdfium.PdfDocument(str(pdf_path))
    page_count = len(doc)
    cache_dir.mkdir(parents=True, exist_ok=True)

    rel_pages: list[str] = []
    for i in range(page_count):
        out_path = cache_dir / f"page-{i + 1:03d}{_PAGE_EXT}"
        pdf_page = doc[i]
        bitmap = pdf_page.render(scale=scale, optimize_mode="print")
        image = bitmap.to_pil()
        # JPEG requires RGB — composite onto white to drop any alpha channel
        if image.mode != "RGB":
            bg = image.new("RGB", image.size, (255, 255, 255))
            bg.paste(image, mask=image.split()[3] if image.mode == "RGBA" else None)
            image = bg
        image.save(str(out_path), format="JPEG", quality=_JPEG_QUALITY, optimize=True)
        rel_pages.append(str(out_path.relative_to(workdir)).replace("\\", "/"))
    doc.close()
    return rel_pages


def _generate_helper(workdir: Path, page_map: dict[str, list[str]]) -> None:
    lines = [
        "// AUTO-GENERATED by SmartTeX — do not edit manually",
        "",
        "#let _smarttex_pdf_pages = (",
    ]
    for pdf_path, pages in page_map.items():
        # Prefix with / so Typst resolves images from --root, not relative to main.typ
        pages_typst = ", ".join(f'"/{p}"' for p in pages)
        lines.append(f'  "{pdf_path}": ({pages_typst},),')
    lines += [
        ")",
        "",
        "#let smarttex-include-pdf(path, width: 100%, pages: none, fit-first-page: false) = {",
        "  let all-pages = _smarttex_pdf_pages.at(path, default: ())",
        "  let selected = if pages == none { all-pages } else {",
        "    pages.map(i => all-pages.at(i - 1))",
        "  }",
        "  for (idx, img) in selected.enumerate() {",
        "    if fit-first-page and idx == 0 {",
        "      block(width: width, height: 1fr, image(img, width: 100%, height: 100%, fit: \"contain\"))",
        "    } else {",
        "      image(img, width: width)",
        "    }",
        "  }",
        "}",
    ]
    helper_path = workdir / _HELPER_PATH
    helper_path.parent.mkdir(parents=True, exist_ok=True)
    helper_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@register
class PdfEmbedJob(PreCompileJob):
    name = "pdf_embed"

    def run(self, project: Any, workdir: Path) -> PreCompileResult:
        from SmartTeX.markup import MarkupType
        if project.markup_type != MarkupType.TYPST:
            return PreCompileResult(job=self.name, success=True)

        manifest = load_manifest(workdir)
        enabled = {k: v for k, v in manifest.items() if v.get("enabled")}

        if not enabled:
            remove_auto_imports_from_all_typst(workdir)
            return PreCompileResult(job=self.name, success=True)

        try:
            import pypdfium2  # noqa: F401
        except ImportError:
            return PreCompileResult(job=self.name, success=False, errors=["pypdfium2 not installed"])

        processed = 0
        skipped = 0
        errors: list[str] = []
        page_map: dict[str, list[str]] = {}
        manifest_dirty = False

        for rel_pdf, entry in enabled.items():
            pdf_path = workdir / rel_pdf
            if not pdf_path.exists():
                errors.append(f"{rel_pdf}: file not found")
                continue

            current_hash = _sha256_file(pdf_path)
            # Include scale in the cache key so quality changes trigger a re-render
            cache_key = f"{current_hash}@{_DEFAULT_SCALE}"
            cache_dir = workdir / _CACHE_DIR / _safe_cache_name(rel_pdf)
            cached_hash = entry.get("last_hash")

            if cached_hash == cache_key and cache_dir.exists():
                pages = sorted(cache_dir.glob(f"page-*{_PAGE_EXT}"), key=lambda p: p.name)
                if pages:
                    page_map[rel_pdf] = [str(p.relative_to(workdir)).replace("\\", "/") for p in pages]
                    skipped += 1
                    continue

            try:
                _render_pdf_pages(pdf_path, cache_dir, workdir)
                pages = sorted(cache_dir.glob(f"page-*{_PAGE_EXT}"), key=lambda p: p.name)
                page_map[rel_pdf] = [str(p.relative_to(workdir)).replace("\\", "/") for p in pages]
                manifest[rel_pdf]["last_hash"] = cache_key
                manifest[rel_pdf]["page_count"] = len(page_map[rel_pdf])
                manifest_dirty = True
                processed += 1
            except Exception as exc:
                errors.append(f"{rel_pdf}: {exc}")

        if page_map:
            _generate_helper(workdir, page_map)
            inject_auto_import_into_reachable_typst(project, workdir, _IMPORT_LINE)

        if manifest_dirty:
            save_manifest(workdir, manifest)

        return PreCompileResult(
            job=self.name,
            success=not errors,
            files_processed=processed,
            files_skipped=skipped,
            errors=errors,
        )
