# Generated by Django 6.0.4 on 2026-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_lib', '0002_template_markup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='template_zips/'),
        ),
    ]
