# Generated by Django 6.0.4 on 2026-05-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_lib', '0003_add_template_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
