# Generated by SmartTeX UI update

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_lib", "0004_content_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="main_file",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
