# Generated by Django 6.0.4 on 2026-04-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mcp', 'MCP'), ('web', 'Web'), ('api', 'API')], default='api', max_length=16)),
                ('operation', models.CharField(max_length=64)),
                ('target', models.CharField(default='main.tex', max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('before_content', models.TextField()),
                ('after_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
