# Generated by Django 6.0.4 on 2026-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_drop_workspace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE projects_project ALTER COLUMN main_file SET DEFAULT ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
