# Generated by Django 6.0.4 on 2026-05-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_project_main_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='category',
            field=models.CharField(choices=[('source', 'Source'), ('assistant', 'Assistant'), ('session_accept', 'Session Accept')], default='source', max_length=20),
        ),
    ]
