# Generated by Django 6.0.4 on 2026-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_github_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_sync_interval_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
