from django.urls import path, re_path

from .views import (
    api_ai_session,
    api_ai_session_accept,
    api_ai_session_compile,
    api_ai_session_diff,
    api_ai_session_discard,
    api_ai_session_finalize,
    api_ai_session_staging_pdf,
    api_ai_session_write,
    api_context_file_detail,
    api_context_files,
    api_longdoc_overview,
    api_longdoc_settings,
    api_longdoc_task_detail,
    api_longdoc_tasks,
    api_mcp_budget,
    api_note_section_detail,
    api_note_sections,
    api_outline_item_detail,
    api_outline_items,
    api_requirement_detail,
    api_requirements,
    api_section_summaries,
)


urlpatterns = [
    path("projects/<int:project_id>/longdoc/settings/", api_longdoc_settings),
    path("projects/<int:project_id>/longdoc/overview/", api_longdoc_overview),
    path("projects/<int:project_id>/context-files/", api_context_files),
    re_path(r"^projects/(?P<project_id>\d+)/context-files/(?P<filename>.+)/$", api_context_file_detail),
    path("projects/<int:project_id>/outline-items/", api_outline_items),
    path("projects/<int:project_id>/outline-items/<int:item_id>/", api_outline_item_detail),
    path("projects/<int:project_id>/tasks/", api_longdoc_tasks),
    path("projects/<int:project_id>/tasks/<int:task_id>/", api_longdoc_task_detail),
    path("projects/<int:project_id>/note-sections/", api_note_sections),
    path("projects/<int:project_id>/note-sections/<int:section_id>/", api_note_section_detail),
    path("projects/<int:project_id>/section-summaries/", api_section_summaries),
    path("projects/<int:project_id>/requirements/", api_requirements),
    path("projects/<int:project_id>/requirements/<int:requirement_id>/", api_requirement_detail),
    path("projects/<int:project_id>/ai-session/", api_ai_session),
    path("projects/<int:project_id>/ai-session/write/", api_ai_session_write),
    path("projects/<int:project_id>/ai-session/compile/", api_ai_session_compile),
    path("projects/<int:project_id>/ai-session/diff/", api_ai_session_diff),
    path("projects/<int:project_id>/ai-session/staging-pdf/", api_ai_session_staging_pdf),
    path("projects/<int:project_id>/ai-session/finalize/", api_ai_session_finalize),
    path("projects/<int:project_id>/ai-session/accept/", api_ai_session_accept),
    path("projects/<int:project_id>/ai-session/discard/", api_ai_session_discard),
    path("projects/<int:project_id>/mcp-budget/", api_mcp_budget),
]
