from django.urls import path, re_path

from .views import (
    api_annotation_detail,
    api_annotations,
    api_change_proposal_accept,
    api_change_proposal_cancel,
    api_change_proposal_diff,
    api_change_proposal_discard,
    api_change_proposal_preview_pdf,
    api_change_proposal_status,
    api_change_proposals,
    api_context_file_detail,
    api_context_files,
    api_document_graph,
    api_longdoc_overview,
    api_longdoc_settings,
    api_longdoc_task_detail,
    api_longdoc_tasks,
    api_mcp_budget,
    api_note_section_detail,
    api_note_sections,
    api_outline_item_detail,
    api_outline_items,
    api_project_ai_request_log,
    api_preview_patch,
    api_requirement_detail,
    api_requirements,
    api_section_summaries,
    api_validate_document_change,
)


urlpatterns = [
    path("projects/<int:project_id>/longdoc/settings/", api_longdoc_settings),
    path("projects/<int:project_id>/longdoc/overview/", api_longdoc_overview),
    path("projects/<int:project_id>/ai-request-log/", api_project_ai_request_log),
    path("projects/<int:project_id>/context-files/", api_context_files),
    re_path(r"^projects/(?P<project_id>\d+)/context-files/(?P<filename>.+)/$", api_context_file_detail),
    path("projects/<int:project_id>/outline-items/", api_outline_items),
    path("projects/<int:project_id>/outline-items/<int:item_id>/", api_outline_item_detail),
    path("projects/<int:project_id>/tasks/", api_longdoc_tasks),
    path("projects/<int:project_id>/tasks/<int:task_id>/", api_longdoc_task_detail),
    path("projects/<int:project_id>/annotations/", api_annotations),
    path("projects/<int:project_id>/annotations/<int:annotation_id>/", api_annotation_detail),
    path("projects/<int:project_id>/note-sections/", api_note_sections),
    path("projects/<int:project_id>/note-sections/<int:section_id>/", api_note_section_detail),
    path("projects/<int:project_id>/section-summaries/", api_section_summaries),
    path("projects/<int:project_id>/requirements/", api_requirements),
    path("projects/<int:project_id>/requirements/<int:requirement_id>/", api_requirement_detail),
    path("projects/<int:project_id>/change-proposals/validate/", api_validate_document_change),
    path("projects/<int:project_id>/change-proposals/", api_change_proposals),
    path("projects/<int:project_id>/change-proposals/status/", api_change_proposal_status),
    path("projects/<int:project_id>/change-proposals/cancel/", api_change_proposal_cancel),
    path("projects/<int:project_id>/change-proposals/diff/", api_change_proposal_diff),
    path("projects/<int:project_id>/change-proposals/preview-pdf/", api_change_proposal_preview_pdf),
    path("projects/<int:project_id>/change-proposals/accept/", api_change_proposal_accept),
    path("projects/<int:project_id>/change-proposals/discard/", api_change_proposal_discard),
    path("projects/<int:project_id>/document-graph/", api_document_graph),
    path("projects/<int:project_id>/preview-patch/", api_preview_patch),
    path("projects/<int:project_id>/mcp-budget/", api_mcp_budget),
]
