# Generated by Django 6.0.4 on 2026-05-27 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_projectversion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('notes_updated', models.BooleanField(default=False)),
                ('requirements_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIBatchChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('change_type', models.CharField(choices=[('modify', 'Modified'), ('create', 'Created'), ('delete', 'Deleted')], max_length=20)),
                ('diff_text', models.TextField(blank=True)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='longdoc.aibatch')),
            ],
            options={
                'ordering': ['batch_id', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('branch_name', models.CharField(max_length=255)),
                ('worktree_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('compiled', 'Compiled'), ('ready_for_review', 'Ready for Review'), ('accepted', 'Accepted'), ('discarded', 'Discarded'), ('expired', 'Expired')], default='active', max_length=30)),
                ('compile_status', models.CharField(choices=[('not_run', 'Not Run'), ('success', 'Success'), ('error', 'Error')], default='not_run', max_length=20)),
                ('compile_log', models.TextField(blank=True)),
                ('staging_pdf_path', models.CharField(blank=True, max_length=500)),
                ('diff_text', models.TextField(blank=True)),
                ('created_by_scope', models.CharField(default='mcp', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='aibatch',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='longdoc.aisession'),
        ),
        migrations.CreateModel(
            name='AssistantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('user', 'User'), ('mcp', 'MCP')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_audit_log', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_read_only', models.BooleanField(default=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLongDocSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('context_enabled', models.BooleanField(default=True)),
                ('outline_enabled', models.BooleanField(default=True)),
                ('tasks_enabled', models.BooleanField(default=True)),
                ('notes_enabled', models.BooleanField(default=True)),
                ('summaries_enabled', models.BooleanField(default=True)),
                ('requirements_enabled', models.BooleanField(default=False)),
                ('ai_sessions_enabled', models.BooleanField(default=True)),
                ('mcp_controlled_access', models.BooleanField(default=True)),
                ('mcp_write_context', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='longdoc_settings', to='projects.project')),
            ],
            options={
                'verbose_name': 'Long-document settings',
                'verbose_name_plural': 'Long-document settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectNoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_sections', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOutlineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('stub', 'Stub'), ('draft', 'Draft'), ('done', 'Done')], default='missing', max_length=20)),
                ('expected_pages', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='longdoc.projectoutlineitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_items', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('coverage', models.CharField(choices=[('unchecked', 'Unchecked'), ('covered', 'Covered'), ('partial', 'Partial'), ('missing', 'Missing')], default='unchecked', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_by', models.CharField(choices=[('user', 'User'), ('mcp', 'MCP')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'req_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=20)),
                ('created_by', models.CharField(choices=[('user', 'User'), ('mcp', 'MCP')], default='user', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='longdoc.aisession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'status', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aibatch',
            name='tasks_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_in_batches', to='longdoc.projecttask'),
        ),
        migrations.CreateModel(
            name='RequirementSectionRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=500)),
                ('outline_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_refs', to='longdoc.projectoutlineitem')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_refs', to='longdoc.projectrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='SectionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=500)),
                ('section_index', models.IntegerField(blank=True, null=True)),
                ('source_file', models.CharField(max_length=500)),
                ('source_line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('summary_text', models.TextField()),
                ('written_by', models.CharField(choices=[('user', 'User'), ('mcp', 'MCP')], max_length=20)),
                ('source_version_number', models.PositiveIntegerField()),
                ('is_stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_summaries', to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['project', 'status'], name='longdoc_ais_project_8d7e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['expires_at'], name='longdoc_ais_expires_59a600_idx'),
        ),
        migrations.AddConstraint(
            model_name='aisession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'compiled', 'ready_for_review'))), fields=('project',), name='longdoc_one_locking_session_per_project'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['project', '-created_at'], name='longdoc_ass_project_161e45_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='longdoc_ass_model_n_2ca273_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcontextfile',
            unique_together={('project', 'filename')},
        ),
        migrations.AlterUniqueTogether(
            name='projectnotesection',
            unique_together={('project', 'heading')},
        ),
        migrations.AddConstraint(
            model_name='projectoutlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='longdoc_outline_level_gte_1'),
        ),
        migrations.AlterUniqueTogether(
            name='projectoutlineitem',
            unique_together={('project', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirement',
            unique_together={('project', 'req_id')},
        ),
        migrations.AddIndex(
            model_name='requirementsectionref',
            index=models.Index(fields=['section_title'], name='longdoc_req_section_6d5111_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementsectionref',
            unique_together={('requirement', 'section_title')},
        ),
        migrations.AddIndex(
            model_name='sectionsummary',
            index=models.Index(fields=['project', 'is_stale'], name='longdoc_sec_project_fb7b30_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectionsummary',
            constraint=models.CheckConstraint(condition=models.Q(('source_line_start__isnull', True), ('source_line_end__isnull', True), ('source_line_end__gte', models.F('source_line_start')), _connector='OR'), name='longdoc_summary_line_range_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionsummary',
            unique_together={('project', 'section_title')},
        ),
    ]
