# Generated by Django 6.0.4 on 2026-06-01 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longdoc', '0005_remove_preparation_enforcement_mode'),
        ('projects', '0013_github_app_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_text', models.TextField(blank=True)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_by', models.CharField(choices=[('user', 'User'), ('mcp', 'MCP')], default='user', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_id', 'status', 'file_name', 'line_start', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectlongdocsettings',
            name='annotations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectannotation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectannotation',
            name='resolved_by_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_annotations', to='longdoc.aisession'),
        ),
        migrations.AddField(
            model_name='projectannotation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='longdoc.projecttask'),
        ),
        migrations.AddIndex(
            model_name='projectannotation',
            index=models.Index(fields=['project', 'status'], name='longdoc_pro_project_61eedb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectannotation',
            index=models.Index(fields=['project', 'file_name'], name='longdoc_pro_project_c98d72_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectannotation',
            constraint=models.CheckConstraint(condition=models.Q(('line_start__isnull', True), ('line_end__isnull', True), ('line_end__gte', models.F('line_start')), _connector='OR'), name='longdoc_annotation_line_range_valid'),
        ),
    ]
