# Generated by Django 6.0.4 on 2026-06-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longdoc', '0006_projectannotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aibatch',
            name='annotations_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_in_batches', to='longdoc.projectannotation'),
        ),
    ]
