# Generated by Django 6.0.4 on 2026-04-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_email_verification(apps, schema_editor):
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    verification_state_model = apps.get_model("accounts", "EmailVerificationState")

    legacy_unverified = user_model.objects.filter(is_active=False, is_superuser=False, is_staff=False)
    for user in legacy_unverified.iterator():
        verification_state_model.objects.get_or_create(user_id=user.id, defaults={"verified_at": None})
        user_model.objects.filter(id=user.id).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverificationtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_legacy_email_verification, migrations.RunPython.noop),
    ]
