TASK_CONTEXT_COMPRESS = "context_compress"
TASK_EDIT_INTENT_CLASSIFY = "edit_intent_classify"
TASK_DIFF_SAFETY_REVIEW = "diff_safety_review"
TASK_COMPILE_LOG_TRIAGE = "compile_log_triage"
TASK_CIRCUIT_BREAKER_EVALUATE = "circuit_breaker_evaluate"

TASK_TYPES = (
    TASK_CONTEXT_COMPRESS,
    TASK_EDIT_INTENT_CLASSIFY,
    TASK_DIFF_SAFETY_REVIEW,
    TASK_COMPILE_LOG_TRIAGE,
    TASK_CIRCUIT_BREAKER_EVALUATE,
)

FEATURE_CONTEXT_COMPRESSOR = "context_compressor"
FEATURE_EDIT_INTENT_CLASSIFIER = "edit_intent_classifier"
FEATURE_DIFF_SAFETY_REVIEWER = "diff_safety_reviewer"
FEATURE_COMPILE_LOG_TRIAGE = "compile_log_triage"
FEATURE_CIRCUIT_BREAKER = "circuit_breaker"

FEATURE_KEYS = (
    FEATURE_CONTEXT_COMPRESSOR,
    FEATURE_EDIT_INTENT_CLASSIFIER,
    FEATURE_DIFF_SAFETY_REVIEWER,
    FEATURE_COMPILE_LOG_TRIAGE,
    FEATURE_CIRCUIT_BREAKER,
)
