TASK_PRE_PROPOSAL_ANALYZE = "pre_proposal_analyze"
TASK_CONTEXT_COMPRESS = "context_compress"
TASK_EDIT_INTENT_CLASSIFY = "edit_intent_classify"
TASK_DIFF_SAFETY_REVIEW = "diff_safety_review"
TASK_COMPILE_LOG_TRIAGE = "compile_log_triage"
TASK_CIRCUIT_BREAKER_EVALUATE = "circuit_breaker_evaluate"
TASK_NAV_FILE_CARD_ENRICH = "nav_file_card_enrich"
TASK_NAV_REGION_CARD_ENRICH = "nav_region_card_enrich"
TASK_NAV_RERANK_TARGETS = "nav_rerank_targets"
TASK_NAV_REPAIR_GUIDANCE = "nav_repair_guidance"
TASK_NAV_SEARCH_RERANK = "nav_search_rerank"

TASK_TYPES = (
    TASK_PRE_PROPOSAL_ANALYZE,
    TASK_CONTEXT_COMPRESS,
    TASK_EDIT_INTENT_CLASSIFY,
    TASK_DIFF_SAFETY_REVIEW,
    TASK_COMPILE_LOG_TRIAGE,
    TASK_CIRCUIT_BREAKER_EVALUATE,
    TASK_NAV_FILE_CARD_ENRICH,
    TASK_NAV_REGION_CARD_ENRICH,
    TASK_NAV_RERANK_TARGETS,
    TASK_NAV_REPAIR_GUIDANCE,
    TASK_NAV_SEARCH_RERANK,
)

FEATURE_PRE_PROPOSAL_ANALYZER = "pre_proposal_analyzer"
FEATURE_CONTEXT_COMPRESSOR = "context_compressor"
FEATURE_EDIT_INTENT_CLASSIFIER = "edit_intent_classifier"
FEATURE_DIFF_SAFETY_REVIEWER = "diff_safety_reviewer"
FEATURE_COMPILE_LOG_TRIAGE = "compile_log_triage"
FEATURE_CIRCUIT_BREAKER = "circuit_breaker"
FEATURE_NAV_INDEX_ENRICH = "nav_index_enrich"
FEATURE_NAV_RERANK = "nav_rerank"
FEATURE_NAV_REPAIR = "nav_repair"

FEATURE_KEYS = (
    FEATURE_PRE_PROPOSAL_ANALYZER,
    FEATURE_CONTEXT_COMPRESSOR,
    FEATURE_EDIT_INTENT_CLASSIFIER,
    FEATURE_DIFF_SAFETY_REVIEWER,
    FEATURE_COMPILE_LOG_TRIAGE,
    FEATURE_CIRCUIT_BREAKER,
    FEATURE_NAV_INDEX_ENRICH,
    FEATURE_NAV_RERANK,
    FEATURE_NAV_REPAIR,
)
